"""initial migration

Revision ID: 26908618a19b
Revises: 
Create Date: 2023-06-28 13:26:19.141882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26908618a19b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letter', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_column('letter')

    # ### end Alembic commands ###
